### ISSUE TITLE
I would like to know more details on how to export test results to Excel.

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/Airtest#298] opened 2019-03-06 10:11 UTC
Remove any following parts if does not have details about

**Describe the bug**
I would like to know more details on how to export test results to Excel.

I would like to know a detailed explanation and example on how to organize the results of the test into Excel.

```
paste traceback here
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**python version:** `python3.5`

**airtest version:** `1.0.22`
> You can get airtest version via `pip freeze` command.

**Smartphone (please complete the following information):**
 - Device: [e.g. google pixel 2]
 - OS: [e.g. Android 8.1]
 - more information if have

**Additional context**

**Comment by Meteorix** [comment] 2019-03-06 10:30
you can do it with third party python libraries, like xlwt. airtest is dedicated for ui automation, but with python, you can do anything.

**Comment by JJunM** [comment] 2019-03-06 10:38
If there is an example, it will be easier to understand and apply.

**Comment by JJunM** [comment] 2019-03-06 10:39
> 당신은 xlwt 같은 제 3 자의 파이썬 라이브러리로 그것을 할 수 있습니다. airtest는 UI 자동화 전용이지만 파이썬에서는 아무 것도 할 수 있습니다.

If there is an example, it will be easier to understand and apply.

**Comment by JJunM** [comment] 2019-03-06 10:43
> you can do it with third party python libraries, like xlwt. airtest is dedicated for ui automation, but with python, you can do anything.

If there is an example, it will be easier to understand and apply.

**Comment by JJunM** [comment] 2019-03-06 11:00
> you can do it with third party python libraries, like xlwt. airtest is dedicated for ui automation, but with python, you can do anything.

If there is an example, it will be easier to understand and apply.

**Comment by JJunM** [comment] 2019-03-06 11:00
> you can do it with third party python libraries, like xlwt. airtest is dedicated for ui automation, but with python, you can do anything.

If there is an example, it will be easier to understand and apply.

**Comment by EraChen233** [comment] 2019-03-11 03:03
1. For the first question, export results to Excel. 
You can read log.txt in path air_name.log/log/log.txt, after  running tests and export report.
![image](https://user-images.githubusercontent.com/5961185/54097934-51c9ca80-43ed-11e9-8018-3905f48eb2c2.png)


2. For the second, send result to the email. Goole "python send email with attachment" and you will get what you need

**Comment by JJunM** [comment] 2019-03-19 05:30
1. For the first question, export results to Excel.
You can read log.txt in path air_name.log/log/log.txt, after running tests and export report.
> The assert value is not saved in log.txt 
I want to extract assert values and save them in Excel. 
I would be happy if you could give me a concrete method.

2. For the second, send result to the email. Goole "python send email with attachment" and you will get what you need

> I want to send an email automatically after the test runs. The test results storage location changes dynamically, and you can not set the email attachment path. Is there any way to set the attachment path?

**Comment by EraChen233** [comment] 2019-03-19 06:37
Duplicate of #328

**Closed** 2019-03-21 00:05 UTC
