### ISSUE TITLE
opencv-contrib-python<=3.4.2.17 pip 只有4.多的包

### ISSUE THREAD

**Issue by alanlonglong** [AirtestProject/Airtest#592] opened 2019-11-05 05:33 UTC
Remove any following parts if does not have details about

**Describe the bug**
A clear and concise description of what the bug is. Or paste traceback below.

```
paste traceback here
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**python version:** `python3.5`

**airtest version:** `1.0.22`
> You can get airtest version via `pip freeze` command.

**Smartphone (please complete the following information):**
 - Device: [e.g. google pixel 2]
 - OS: [e.g. Android 8.1]
 - more information if have

**Additional context**

**Comment by dinghongyi** [comment] 2019-11-26 09:34
Duplicate of #573

**Closed by dinghongyi** 2019-11-26 09:34 UTC
