### ISSUE TITLE
python项目引入了airtest和pocoui,打包成exe的时候报如下错误

### ISSUE THREAD

**Issue by huxiao123** [AirtestProject/Airtest#657] opened 2019-12-26 09:56 UTC
python项目引入了airtest和pocoui,打包成exe的时候报如下错误
使用的pyinstaller  打包

python 版本: python3.5.0

airtest 版本: 1.1.1

设备:

系统: win 10

=============================================
Traceback (most recent call last):
  File "Qt.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "d:\program files (x86)\python3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "untitled.py", line 8, in <module>
  File "site-packages\poco\drivers\android\uiautomation.py", line 158, in __init__
  File "site-packages\airtest\core\api.py", line 63, in connect_device
  File "site-packages\airtest\core\api.py", line 33, in init_device
  File "site-packages\airtest\core\android\android.py", line 32, in __init__
  File "site-packages\airtest\core\android\android.py", line 60, in get_default_device
  File "site-packages\airtest\core\android\adb.py", line 215, in devices
  File "site-packages\airtest\core\android\adb.py", line 172, in cmd
  File "site-packages\airtest\core\android\adb.py", line 151, in start_cmd
  File "subprocess.py", line 950, in __init__
  File "subprocess.py", line 1220, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
============================================================
[pyexe.zip](https://github.com/AirtestProject/Airtest/files/4002144/pyexe.zip)

**Comment by yimelia** [comment] 2019-12-26 10:45
Duplicate of https://github.com/AirtestProject/Poco/issues/328

这种问题请自行解决，报错信息已经写得比较清楚了。运行的流程是会去读取脚本文件，但是你打包的exe没有包含脚本的“原文件”，所以它找不到。
可以考虑按照原路径，直接把脚本文件拷贝过去。

**Closed by yimelia** 2019-12-26 10:45 UTC

**Comment by wangvic21** [comment] 2022-06-10 11:40
这里我看了下，是找不到adb。
