### ISSUE TITLE
Multi Scripts run with multi devices

### ISSUE THREAD

**Issue by Skisperd** [AirtestProject/Airtest#344] opened 2019-04-02 21:36 UTC
Thanks for the help with running using the multi-device-runner-master. But I still can not run more than 1 script.
The multi-device-runner-master only runs 1 at a time. How can I run more than 4 scripts in sequence?

**Comment by EraChen233** [comment] 2019-04-03 01:59
Duplicate of #300

**Closed by EraChen233** 2019-04-03 01:59 UTC
